# PyMVPA Tutorial  

Here is our intro from 9/25/17. Importantly, you all took some steps to get things running and loading proper, please take note of those somewhere you can keep track of. 

This tutorial goes over the bones of PyMVPA. Read about object oriented programming, classification, and RSA for refreshers on conceptual issues. Eg, Jim Haxby's 'mind-reading' paper, Kriegeskorte's 2008 RSA paper.

First, we need to import PyMVPA. Remember this import command pulls in everything to be called immediately, as opposed to a typical import command where we'd have to reference the module each call. Read and learn the difference in types of import commands in python.

In [5]:
from mvpa2.suite import *

Remember, its normal for warnings to appear. Main concern is if an error is raised, which kills the import. 

To test the import, teach looking at documentation, and figure out how to load our data, let's look at the h5load function.

In [2]:
help(h5load)

Help on function h5load in module mvpa2.base.hdf5:

h5load(filename, name=None)
    Loads the content of an HDF5 file that has been stored by `h5save()`.
    
    This is a convenience wrapper around `hdf2obj()`. Please see its
    documentation for more details.
    
    Parameters
    ----------
    filename : str
      Name of the file to open and load its content.
    name : str
      Name of a specific object to load from the file.
    
    Returns
    -------
    instance
      An object of whatever has been stored in the file.



This and other help/doc calls can make your life easier, so learn them, and how to navigate documentation online, email listserv threads, and places such as stack overflow for help.

Now, remember, hdf5/h5 tools are great because you can save any python object as a file, then load it back. For instance, let's save a numpy array locally, then load it back in.

In [3]:
tom = np.array([[1,2,3],[4,5,6]])
h5save('tom_array.hdf5',tom,compression=9)
del(tom)
tom = h5load('tom_array.hdf5')
print(tom)

[[1 2 3]
 [4 5 6]]


**Super cool.** Now, let's load in our data. Change the path to yours!

In [3]:
data = h5load('./mufasa_locale/scc/final_Current/roi_r2_final/scc_Tzs_cut.hdf5')

Remember, we are working with the data in this special format to accomodate PyMVPAw later. This is a dictionary, where each key is a subject number, and each value their pymvpa dataset. Let's look at our subjects, and move one to the side to analyze here:

In [5]:
type(data) # checking object types is important and helps keep up with what you're looking at and if its proper
print(data.keys()) # here's our subject IDs
ds = data['586'].copy() # here we are using .copy() to make a hard separate copy in memory
print(type(ds))

['586', '587', '584', '592', '582', '583', '580', '590', '591', '581', '577', '579', '575', '589', '578', '576', '588', '585', '593', '574']
<class 'mvpa2.datasets.base.Dataset'>


Now let's get a good look at a PyMVPA dataset. Remember, there are dataset attributes, feature attributes, and sample attributes. Read about them in PyMVPA doc more. We can look at them like this:

In [6]:
# dataset attributes
print ds.a
# feature attributes
print ds.fa
# sample attributes
print ds.sa

<DatasetAttributesCollection: imgaffine,imghdr,imgtype,mapper,subjID,voxel_dim,voxel_eldim>
<FeatureAttributesCollection: voxel_indices>
<SampleAttributesCollection: chunks,targets,time_coords,time_indices>


That's the list of them in this dataset, but let's look at them up close. Remember, you can also tab out to get an idea of what attributes any object has in python, just type the object name, a period (eg, 'ds.') then tab out to see options. Every object has attributes and methods. Google it.

*Important side note, remember there are two ways to reference certain sample attributes, with a brack index like a dictionary, or the attribute data directly in the normal period notation. The period notation, like below, returns the actual object used as attributes, whereas the brackets allow you to refer to them in a way that you can replace them.*

In [7]:
# to change attributes, you need to reference them with brackets as strings, period calls only return values

print ds.shape # whats our dataset shape, how many samples (TRs/observations) and features (voxels)
ds.a['subjID'] = '999' # let's see how you can change an attribute, eg, add a subject ID 
print ds.a.subjID
print ds.fa.voxel_indices
print ds.sa.targets,ds.sa.chunks
# or
print ds.UT,ds.UC # shortcuts to see unique targets and chunks
print ds.samples # reference to actualy data object directly

(72, 86474)
999
[[ 5 28 23]
 [ 5 29 21]
 [ 5 29 22]
 ..., 
 [55 40 25]
 [55 41 24]
 [55 41 25]]
['an' 'ap' 'bn' 'bp' 'an' 'ap' 'bn' 'bp' 'an' 'ap' 'bn' 'bp' 'an' 'ap' 'bn'
 'bp' 'an' 'ap' 'bn' 'bp' 'an' 'ap' 'bn' 'bp' 'ac' 'bc' 'wc' 'hc' 'ac' 'bc'
 'wc' 'hc' 'ac' 'bc' 'wc' 'hc' 'ac' 'bc' 'wc' 'hc' 'ac' 'bc' 'wc' 'hc' 'ac'
 'bc' 'wc' 'hc' 'as' 'bs' 'cs' 'ss' 'as' 'bs' 'cs' 'ss' 'as' 'bs' 'cs' 'ss'
 'as' 'bs' 'cs' 'ss' 'as' 'bs' 'cs' 'ss' 'as' 'bs' 'cs' 'ss'] [ 1.  1.  1.  1.  2.  2.  2.  2.  3.  3.  3.  3.  4.  4.  4.  4.  5.  5.
  5.  5.  6.  6.  6.  6.  1.  1.  1.  1.  2.  2.  2.  2.  3.  3.  3.  3.
  4.  4.  4.  4.  5.  5.  5.  5.  6.  6.  6.  6.  1.  1.  1.  1.  2.  2.
  2.  2.  3.  3.  3.  3.  4.  4.  4.  4.  5.  5.  5.  5.  6.  6.  6.  6.]
['ac' 'an' 'ap' 'as' 'bc' 'bn' 'bp' 'bs' 'cs' 'hc' 'ss' 'wc'] [ 1.  2.  3.  4.  5.  6.]
[[ 1.56895947 -0.00515484 -0.45095265 ...,  0.03682332 -2.27489138
  -0.70922989]
 [ 1.05142415  1.14230013  1.65540886 ...,  0.69169277 -0.16223796
  -0.647

In [8]:
# OR
print ds.summary()

Dataset: 72x86474@float32, <sa: chunks,targets,time_coords,time_indices>, <fa: voxel_indices>, <a: imgaffine,imghdr,imgtype,mapper,subjID,voxel_dim,voxel_eldim>
stats: mean=-3.08919e-09 std=0.909753 var=0.827651 min=-3.29849 max=3.28968

Counts of targets in each chunk:
  chunks\targets  ac  an  ap  as  bc  bn  bp  bs  cs  hc  ss  wc
                 --- --- --- --- --- --- --- --- --- --- --- ---
       1.0        1   1   1   1   1   1   1   1   1   1   1   1
       2.0        1   1   1   1   1   1   1   1   1   1   1   1
       3.0        1   1   1   1   1   1   1   1   1   1   1   1
       4.0        1   1   1   1   1   1   1   1   1   1   1   1
       5.0        1   1   1   1   1   1   1   1   1   1   1   1
       6.0        1   1   1   1   1   1   1   1   1   1   1   1

Summary for targets across chunks
  targets mean std min max #chunks
    ac      1   0   1   1     6
    an      1   0   1   1     6
    ap      1   0   1   1     6
    as      1   0   1   1     6
    bc      1   0

In [11]:
# and to see each sample up close....
for i in ds:
    print i.sa.time_indices, i.sa.chunks, i.shape,i.sa.targets,i.samples

[0] [ 1.] (1, 86474) ['an'] [[ 1.56895947 -0.00515484 -0.45095265 ...,  0.03682332 -2.27489138
  -0.70922989]]
[1] [ 1.] (1, 86474) ['ap'] [[ 1.05142415  1.14230013  1.65540886 ...,  0.69169277 -0.16223796
  -0.64775032]]
[2] [ 1.] (1, 86474) ['bn'] [[ 0.5766384   0.60853904 -0.92059129 ...,  0.79704809  0.00769751
  -0.1766022 ]]
[3] [ 1.] (1, 86474) ['bp'] [[-0.09207978 -0.76136887  0.21937369 ...,  0.59290373 -0.20790583
  -0.37358156]]
[4] [ 2.] (1, 86474) ['an'] [[ 0.22106083 -0.5769217  -0.47130743 ...,  1.63640285 -0.93795413
   0.90210861]]
[5] [ 2.] (1, 86474) ['ap'] [[-0.51109815 -1.1174134  -0.7583968  ...,  0.96687639 -0.12521978
   1.05656707]]
[6] [ 2.] (1, 86474) ['bn'] [[ 1.46095335 -1.11682534 -0.74013501 ...,  1.0684706  -0.6295175
   1.34438181]]
[7] [ 2.] (1, 86474) ['bp'] [[-0.24016844 -0.93364656 -0.77025861 ...,  0.70631087  0.25070012
  -0.71538353]]
[8] [ 3.] (1, 86474) ['an'] [[ 1.11752272  1.98873639  0.962524   ..., -1.16408062 -1.57001805
  -2.03287005]]
[9

# Analyses

First, let's whip this data into shape. We want to just look at stereotype patterns. 


- an ap bn bp | asian black pos neg
- ac bc | asian black category
- as bs | asian black face

So let's cut out anything we don't need. To do so, we'll steal from PyMVPAw quickly...

In [14]:
for om in ['ac','as', 'bc', 'bs', 'cs', 'hc', 'ss', 'wc']:
    ds = ds[ds.sa.targets != om]

print ds.UT,ds.shape # the resulting dataset is now trimmed

['an' 'ap' 'bn' 'bp'] (24, 86474)


# RSA

First, let's perform RSA. Here we correlate a theoretical model where valence is what drives pattern similarity. Ie, 'an' and 'bn' are more similar to one another than 'ap' and 'bp'. We correlate this dissimilarity matrix with the representational similarity matrix (wholebrain neural pattern similarity between these conditions). Read up Krieg 2008 for more detail.

In [15]:
ds_mgs = mean_group_sample(['targets'])(ds) # calculate mean sample (neural pattern) per target
print ds_mgs.shape,ds_mgs.UT # hows the data look now?

# make a theoretical model, this is in the order data is in the dataset! look at data targets/UT for an idea. 
# Usually alphabetical after mean group sampling
valDM = squareform ( np.array([[0,1,0,1],  
                  [1,0,1,0],
                  [0,1,0,1],
                  [1,0,1,0]]) )
RDM = pdist(ds_mgs,metric='correlation') # get similarity of neural patterns in correlation distance
print squareform(RDM) #what do these DMs look like?
print squareform(valDM)

print np.corrcoef(RDM,valDM) #correlate them!

(4, 86474) ['an' 'ap' 'bn' 'bp']
[[ 0.          0.71989384  0.70512579  0.67112384]
 [ 0.71989384  0.          0.64340398  0.60258555]
 [ 0.70512579  0.64340398  0.          0.60428371]
 [ 0.67112384  0.60258555  0.60428371  0.        ]]
[[ 0.  1.  0.  1.]
 [ 1.  0.  1.  0.]
 [ 0.  1.  0.  1.]
 [ 1.  0.  1.  0.]]
[[ 1.          0.06037519]
 [ 0.06037519  1.        ]]


Wowzer. Pearson *r* = .06.

# Classification

Next guy. Try to remember similarites and differences between classification and RSA, pros and cons, etc. Read up.

We will here try to see if we can classify above chance these four stereotype conditions. We'll use a linear SVM, and leave-one-out cross-validation scheme. Google those too.

First, we remove invariant features that might choke up some classifiers sometimes.

In [17]:
remapper = ds.copy()
inv_mask = ds.samples.std(axis=0)>0
sfs = StaticFeatureSelection(slicearg=inv_mask)
sfs.train(remapper)
data_m = remove_invariant_features(ds)
print np.mean(inv_mask) # % of data kept / 

0.828295210121


Now for the meat. Here we create objects holding all our plans, linear SVM, our CV scheme/partitioner, and a little magic to get accuracy back instead of classifier error. Then, we run the analysis!

In [18]:
cv = CrossValidation(LinearCSVMC(), NFoldPartitioner(), 
                     enable_ca=['stats'], 
                     errorfx=lambda p, t: np.mean(p == t))

res = cv(data_m)

In [20]:
print res.summary()
print np.mean(res.samples) - (1.0 / len(data_m.UT)) # % above chance accuracy

Dataset: 6x1@float64, <sa: cvfolds> stats: mean=0.333333 std=0.186339 var=0.0347222 min=0 max=0.5

0.0833333333333


8% of chance, woooooooah. How about, like, locally distributed across the brain dome?

# Searchlights

Searchlights. Check out Kriegeskorte (circa 2005 - 2009?). This takes forever-ever, but, here's the code.

In [4]:
if __debug__: debug.active += ["SLC"] # print progress
# take out invariant features
ds = data['586'].copy()
remapper = ds.copy()
inv_mask = ds.samples.std(axis=0)>0
sfs = StaticFeatureSelection(slicearg=inv_mask)
sfs.train(remapper)
ds = remove_invariant_features(ds)
cv=CrossValidation(LinearCSVMC(), NFoldPartitioner(), 
                   enable_ca=['stats'], 
                   errorfx=lambda p, t: np.mean(p == t))

sl = sphere_searchlight(cv, radius=3, postproc=mean_sample())
slr = sl(ds)


[SLC] DBG:                         Starting computing block for 71626 elements
[SLC] DBG:                         +0:00:03 _______[0%]_______ -4:37:33  ROI 14 (14/71626), 55 features

KeyboardInterrupt: 

So I'm not waiting for that, but, from that, we go here:

In [154]:
res = sfs.reverse(slr).samples - (1.0/len(ds.UT)) # remove chance, and get back in its pre feature selection form
print res # check it

# save it, and look in afni
nimg = map2nifti(data=ds,dataset=data['586'])
nimg.to_filename('586_stereoclass.nii')

<Dataset: 1x378@float64, <sa: cvfolds>, <fa: center_ids>, <a: mapper>>


Well that does it! You can now look at the results in AFNI. You can also do group level tests, etc. However, we will save this for later when we move into PyMVPAw, which takes all of this code and wraps it up into single functions.

Also, we will soon work to get python to display plots via nilearn:

![image.png](http://nilearn.github.io/_images/sphx_glr_plot_neurovault_meta_analysis_thumb.png)